// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2JgkjEphDy3ZsI1ZzqhSmc5Fs1c2MRGk',
    appId: '1:610813303399:web:a243890cafc3fa45ff12c2',
    messagingSenderId: '610813303399',
    projectId: 'polynom-puzzle',
    authDomain: 'polynom-puzzle.firebaseapp.com',
    storageBucket: 'polynom-puzzle.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvLEWtwXIyuNsgaHR7y7JCdvkHNZUyW8s',
    appId: '1:610813303399:android:72ca31b9ee2f6989ff12c2',
    messagingSenderId: '610813303399',
    projectId: 'polynom-puzzle',
    storageBucket: 'polynom-puzzle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJX0vSntWf0QKZ8mpPlvzfFepZ_I9g9KA',
    appId: '1:610813303399:ios:94a8681c2acf7de2ff12c2',
    messagingSenderId: '610813303399',
    projectId: 'polynom-puzzle',
    storageBucket: 'polynom-puzzle.appspot.com',
    iosClientId: '610813303399-ip5il8lr9h6s40uug9j8q4kj5n4q1sou.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
